// src/routes/contact/+page.svelte
<section class="section-pad">
  <div class="container-narrow">
    <header class="mb-8 md:mb-12 text-center">
      <h2 class="heading-display text-3xl md:text-5xl text-brand-soft mb-3 md:mb-4">Contact</h2>
      <p class="text-base md:text-lg text-content-subtle">
        Let's capture your special moments together
      </p>
    </header>

    <div class="grid md:grid-cols-2 gap-6 md:gap-8 mb-8 md:mb-12">
      <div class="bg-card p-6 md:p-8 border-2 border-brand-border hover:shadow-lg transition-shadow">
        <div class="flex items-center justify-center mb-4 md:mb-6 text-brand-soft">
          <svg
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="1.5"
            stroke-linecap="round"
            stroke-linejoin="round"
            class="w-10 md:w-12 h-10 md:h-12"
            aria-hidden="true"
          >
            <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72c.13.96.36 1.9.7 2.81a2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45c.91.34 1.85.57 2.81.7A2 2 0 0 1 22 16.92Z" />
          </svg>
        </div>
        <h3 class="text-xl md:text-2xl text-brand-soft text-center mb-3 md:mb-4">Call or Text</h3>
        <a
          href="tel:629-308-4828"
          class="block text-lg md:text-xl text-center text-content-subtle hover:text-brand-soft transition-colors mb-3 md:mb-4"
        >
          629-308-4828
        </a>
        <p class="text-xs md:text-sm text-content-subtle text-center">
          Available for calls and messages
        </p>
      </div>

      <div class="bg-card p-6 md:p-8 border-2 border-brand-border hover:shadow-lg transition-shadow">
        <div class="flex items-center justify-center mb-4 md:mb-6 text-brand-soft">
          <svg
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="1.5"
            stroke-linecap="round"
            stroke-linejoin="round"
            class="w-10 md:w-12 h-10 md:h-12"
            aria-hidden="true"
          >
            <rect x="2" y="4" width="20" height="16" rx="2" />
            <path d="m22 6-10 7L2 6" />
          </svg>
        </div>
        <h3 class="text-xl md:text-2xl text-brand-soft text-center mb-3 md:mb-4">Email</h3>
        <a
          href="mailto:Jovy.thomas@gmail.com"
          class="block text-base md:text-xl text-center text-content-subtle hover:text-brand-soft transition-colors mb-3 md:mb-4 break-all"
        >
          Jovy.thomas@gmail.com
        </a>
        <p class="text-xs md:text-sm text-content-subtle text-center">
          Send me your inquiries anytime
        </p>
      </div>
    </div>

    <div class="grid md:grid-cols-2 gap-6 md:gap-8 mb-8 md:mb-12">
      <div class="bg-surface p-6 md:p-8 border-l-4 border-brand-soft">
        <div class="flex items-center mb-3 md:mb-4 text-brand-soft">
          <svg
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="1.5"
            stroke-linecap="round"
            stroke-linejoin="round"
            class="w-6 md:w-8 h-6 md:h-8 mr-2 md:mr-3"
            aria-hidden="true"
          >
            <circle cx="12" cy="12" r="10" />
            <path d="M12 6v6l4 2" />
          </svg>
          <h3 class="text-lg md:text-xl text-brand-soft">Working Hours</h3>
        </div>
        <p class="text-base md:text-lg text-content-subtle mb-2">Monday - Friday</p>
        <p class="text-xl md:text-2xl text-brand-soft">9:00 AM - 5:00 PM</p>
        <p class="text-xs md:text-sm text-content-subtle mt-2 md:mt-3">Central Time (CT)</p>
      </div>

      <div class="bg-surface p-6 md:p-8 border-l-4 border-brand-soft">
        <div class="flex items-center mb-3 md:mb-4 text-brand-soft">
          <svg
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="1.5"
            stroke-linecap="round"
            stroke-linejoin="round"
            class="w-6 md:w-8 h-6 md:h-8 mr-2 md:mr-3"
            aria-hidden="true"
          >
            <path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5Z" />
          </svg>
          <h3 class="text-lg md:text-xl text-brand-soft">Response Time</h3>
        </div>
        <p class="text-base md:text-lg text-content-subtle mb-2">We typically respond within</p>
        <p class="text-xl md:text-2xl text-brand-soft">24 Hours</p>
        <p class="text-xs md:text-sm text-content-subtle mt-2 md:mt-3">on business days</p>
      </div>
    </div>

    <div class="bg-card p-6 md:p-8 border-2 border-brand-soft text-center">
      <h3 class="text-xl md:text-2xl text-brand-soft mb-3 md:mb-4">Ready to Book Your Session?</h3>
      <p class="text-sm md:text-base text-content-subtle mb-4 md:mb-6">
        Whether you're interested in family portraits, maternity photography, or capturing your
        child's precious moments, I'd love to hear from you. Reach out via phone or email, and
        let's create beautiful memories together.
      </p>
      <div class="flex flex-col sm:flex-row gap-3 md:gap-4 justify-center">
        <a
          href="tel:629-308-4828"
          class="inline-flex items-center justify-center bg-brand-soft text-content-inverse px-6 md:px-8 py-2.5 md:py-3 text-sm md:text-base hover:bg-brand-strong transition-colors"
        >
          Call Now
        </a>
        <a
          href="mailto:Jovy.thomas@gmail.com"
          class="inline-flex items-center justify-center bg-card text-brand-soft px-6 md:px-8 py-2.5 md:py-3 text-sm md:text-base border-2 border-brand-soft hover:bg-surface transition-colors"
        >
          Send Email
        </a>
      </div>
    </div>

    <div class="mt-8 md:mt-12 text-center p-4 md:p-6 bg-page border border-brand-border">
      <p class="text-xs md:text-sm text-content-subtle">
        Serving Hendersonville, Gallatin, and surrounding areas in Tennessee
      </p>
    </div>
  </div>
</section>

// src/components/Contact.tsx
import { Phone, Clock, Mail, MessageCircle } from "lucide-react";

export function Contact() {
  return (
    <section className="py-8 md:py-12 px-4">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="mb-8 md:mb-12 text-center">
          <h2 className="text-3xl md:text-5xl text-[#8b7355] mb-3 md:mb-4">Contact</h2>
          <p
            className="text-base md:text-lg text-[#6b6b6b]"
            style={{ fontFamily: "'Courier New', monospace" }}
          >
            Let's capture your special moments together
          </p>
        </div>

        {/* Contact Information Cards */}
        <div className="grid md:grid-cols-2 gap-6 md:gap-8 mb-8 md:mb-12">
          {/* Phone Contact */}
          <div className="bg-white p-6 md:p-8 border-2 border-[#c4b8a4] hover:shadow-lg transition-shadow">
            <div className="flex items-center justify-center mb-4 md:mb-6">
              <Phone className="w-10 md:w-12 h-10 md:h-12 text-[#8b7355]" />
            </div>
            <h3
              className="text-xl md:text-2xl text-[#8b7355] text-center mb-3 md:mb-4"
              style={{ fontFamily: "'Courier New', monospace" }}
            >
              Call or Text
            </h3>
            <a
              href="tel:629-308-4828"
              className="block text-lg md:text-xl text-center text-[#6b6b6b] hover:text-[#8b7355] transition-colors mb-3 md:mb-4"
              style={{ fontFamily: "'Courier New', monospace" }}
            >
              629-308-4828
            </a>
            <p
              className="text-xs md:text-sm text-[#6b6b6b] text-center"
              style={{ fontFamily: "'Courier New', monospace" }}
            >
              Available for calls and messages
            </p>
          </div>

          {/* Email Contact */}
          <div className="bg-white p-6 md:p-8 border-2 border-[#c4b8a4] hover:shadow-lg transition-shadow">
            <div className="flex items-center justify-center mb-4 md:mb-6">
              <Mail className="w-10 md:w-12 h-10 md:h-12 text-[#8b7355]" />
            </div>
            <h3
              className="text-xl md:text-2xl text-[#8b7355] text-center mb-3 md:mb-4"
              style={{ fontFamily: "'Courier New', monospace" }}
            >
              Email
            </h3>
            <a
              href="mailto:Jovy.thomas@gmail.com"
              className="block text-base md:text-xl text-center text-[#6b6b6b] hover:text-[#8b7355] transition-colors mb-3 md:mb-4 break-all"
              style={{ fontFamily: "'Courier New', monospace" }}
            >
              Jovy.thomas@gmail.com
            </a>
            <p
              className="text-xs md:text-sm text-[#6b6b6b] text-center"
              style={{ fontFamily: "'Courier New', monospace" }}
            >
              Send me your inquiries anytime
            </p>
          </div>
        </div>

        {/* Business Hours and Response Time */}
        <div className="grid md:grid-cols-2 gap-6 md:gap-8 mb-8 md:mb-12">
          {/* Working Hours */}
          <div className="bg-[#f5f2ec] p-6 md:p-8 border-l-4 border-[#8b7355]">
            <div className="flex items-center mb-3 md:mb-4">
              <Clock className="w-6 md:w-8 h-6 md:h-8 text-[#8b7355] mr-2 md:mr-3" />
              <h3
                className="text-lg md:text-xl text-[#8b7355]"
                style={{ fontFamily: "'Courier New', monospace" }}
              >
                Working Hours
              </h3>
            </div>
            <p
              className="text-base md:text-lg text-[#6b6b6b] mb-2"
              style={{ fontFamily: "'Courier New', monospace" }}
            >
              Monday - Friday
            </p>
            <p
              className="text-xl md:text-2xl text-[#8b7355]"
              style={{ fontFamily: "'Courier New', monospace" }}
            >
              9:00 AM - 5:00 PM
            </p>
            <p
              className="text-xs md:text-sm text-[#6b6b6b] mt-2 md:mt-3"
              style={{ fontFamily: "'Courier New', monospace" }}
            >
              Central Time (CT)
            </p>
          </div>

          {/* Response Time */}
          <div className="bg-[#f5f2ec] p-6 md:p-8 border-l-4 border-[#8b7355]">
            <div className="flex items-center mb-3 md:mb-4">
              <MessageCircle className="w-6 md:w-8 h-6 md:h-8 text-[#8b7355] mr-2 md:mr-3" />
              <h3
                className="text-lg md:text-xl text-[#8b7355]"
                style={{ fontFamily: "'Courier New', monospace" }}
              >
                Response Time
              </h3>
            </div>
            <p
              className="text-base md:text-lg text-[#6b6b6b] mb-2"
              style={{ fontFamily: "'Courier New', monospace" }}
            >
              We typically respond within
            </p>
            <p
              className="text-xl md:text-2xl text-[#8b7355]"
              style={{ fontFamily: "'Courier New', monospace" }}
            >
              24 Hours
            </p>
            <p
              className="text-xs md:text-sm text-[#6b6b6b] mt-2 md:mt-3"
              style={{ fontFamily: "'Courier New', monospace" }}
            >
              on business days
            </p>
          </div>
        </div>

        {/* Call to Action */}
        <div className="bg-white p-6 md:p-8 border-2 border-[#8b7355] text-center">
          <h3
            className="text-xl md:text-2xl text-[#8b7355] mb-3 md:mb-4"
            style={{ fontFamily: "'Courier New', monospace" }}
          >
            Ready to Book Your Session?
          </h3>
          <p
            className="text-sm md:text-base text-[#6b6b6b] mb-4 md:mb-6"
            style={{ fontFamily: "'Courier New', monospace" }}
          >
            Whether you're interested in family portraits, maternity photography, or capturing your
            child's precious moments, I'd love to hear from you. Reach out via phone or email, and
            let's create beautiful memories together.
          </p>
          <div className="flex flex-col sm:flex-row gap-3 md:gap-4 justify-center">
            <a
              href="tel:629-308-4828"
              className="bg-[#8b7355] text-white px-6 md:px-8 py-2.5 md:py-3 text-sm md:text-base hover:bg-[#6b5842] transition-colors"
              style={{ fontFamily: "'Courier New', monospace" }}
            >
              Call Now
            </a>
            <a
              href="mailto:Jovy.thomas@gmail.com"
              className="bg-white text-[#8b7355] px-6 md:px-8 py-2.5 md:py-3 text-sm md:text-base border-2 border-[#8b7355] hover:bg-[#f5f2ec] transition-colors"
              style={{ fontFamily: "'Courier New', monospace" }}
            >
              Send Email
            </a>
          </div>
        </div>

        {/* Location Info */}
        <div className="mt-8 md:mt-12 text-center p-4 md:p-6 bg-[#e8e4d8] border border-[#c4b8a4]">
          <p
            className="text-xs md:text-sm text-[#6b6b6b]"
            style={{ fontFamily: "'Courier New', monospace" }}
          >
            Serving Hendersonville, Gallatin, and surrounding areas in Tennessee
          </p>
        </div>
      </div>
    </section>
  );
}
