// src/lib/components/Header.svelte
<script lang="ts">
  import { page } from '$app/stores';
  import { navItems, isActive } from '$lib/nav';

  let mobileMenuOpen = $state(false);

  const pathname = $derived($page.url.pathname);
</script>

<header class="bg-page">
  <div class="container-wide px-4 py-4 md:py-6">
    <div class="flex items-center justify-between">
      <div class="hidden md:block flex-shrink-0">
        <img
          src="/peoples-choice-badge.avif"
          alt="GLOW Finalist Award"
          class="w-20 lg:w-32 h-20 lg:h-32 object-contain"
        />
      </div>

      <div class="flex-1 flex flex-col items-center px-2">
        <div class="mb-2 md:mb-4">
          <img src="/balloons.avif" alt="Hot air balloons" class="h-10 md:h-16 w-auto" />
        </div>

        <h1
          class="heading-display text-2xl sm:text-3xl md:text-4xl text-brand-soft mb-1 md:mb-2 text-center"
        >
          JOVY THOMAS VISUALS
        </h1>

        <p class="text-xs md:text-sm text-content-muted mb-2 md:mb-3 text-center">
          Preserve those moments forever...
        </p>

        <p class="text-xs md:text-sm text-content text-center px-2">
          Hendersonville-TN-Portrait and Small event Photographer
        </p>
      </div>

      <div class="hidden md:block flex-shrink-0">
        <img
          src="/portrait-master-badge.avif"
          alt="Portrait Masters Bronze 2021"
          class="w-20 lg:w-32 h-20 lg:h-32 object-contain"
        />
      </div>
    </div>
  </div>

  <nav class="border-t border-brand-border">
    <div class="container-wide px-4">
      <div class="md:hidden flex justify-center py-2">
        <button
          type="button"
          onclick={() => (mobileMenuOpen = !mobileMenuOpen)}
          class="flex items-center gap-2 px-4 py-2 text-brand-soft border border-brand-border bg-card text-sm"
          aria-expanded={mobileMenuOpen}
          aria-controls="mobile-menu"
        >
          <span aria-hidden="true">{mobileMenuOpen ? '✕' : '☰'}</span>
          <span>Menu</span>
        </button>
      </div>

      {#if mobileMenuOpen}
        <div id="mobile-menu" class="md:hidden pb-4">
          <ul class="flex flex-col items-center gap-2">
            {#each navItems as item (item.href)}
              {@const active = isActive(pathname, item.href)}
              <li class="w-full max-w-xs">
                {#if active}
                  <a
                    href={item.href}
                    onclick={() => (mobileMenuOpen = false)}
                    class="block w-full text-center px-4 py-2 text-sm transition-colors border border-brand-border text-brand-soft bg-surface"
                    aria-current="page"
                  >
                    {item.label}
                  </a>
                {:else}
                  <a
                    href={item.href}
                    onclick={() => (mobileMenuOpen = false)}
                    class="block w-full text-center px-4 py-2 text-sm transition-colors border border-brand-border text-content bg-card hover:text-brand-soft hover:bg-surface"
                  >
                    {item.label}
                  </a>
                {/if}
              </li>
            {/each}
          </ul>
        </div>
      {/if}

      <ul class="hidden md:flex items-center justify-center gap-1 py-2 flex-wrap">
        {#each navItems as item (item.href)}
          {@const active = isActive(pathname, item.href)}
          <li>
            {#if active}
              <a
                href={item.href}
                class="block px-3 py-1 text-xs transition-colors border border-brand-border text-brand-soft bg-surface"
                aria-current="page"
              >
                {item.label}
              </a>
            {:else}
              <a
                href={item.href}
                class="block px-3 py-1 text-xs transition-colors border border-brand-border text-content bg-card hover:text-brand-soft hover:bg-surface"
              >
                {item.label}
              </a>
            {/if}
          </li>
        {/each}
      </ul>
    </div>
  </nav>
</header>

// src/components/Header.tsx
import { useState } from "react";
import { Menu, X } from "lucide-react";
import { balloonImage, portraitMasterBadge, peoplesChoiceBadge } from "../assets/images";

interface HeaderProps {
  onNavigate: (page: string) => void;
  currentPage: string;
}

export function Header({ onNavigate, currentPage }: HeaderProps) {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const menuItems = [
    "HOME",
    "GALLERY",
    "SMALL EVENT PHOTOGRAPHY",
    "PACKAGES",
    "ABOUT ME",
    "MENTIONS",
    "CONTACT",
  ];

  return (
    <header className="bg-[#e8e4d8]">
      {/* Top section with balloons and branding */}
      <div className="max-w-7xl mx-auto px-4 py-4 md:py-6">
        <div className="flex items-center justify-between">
          {/* Left badge - hidden on mobile, visible on md+ */}
          <div className="hidden md:block flex-shrink-0">
            <img
              src={peoplesChoiceBadge}
              alt="GLOW Finalist Award"
              className="w-20 lg:w-32 h-20 lg:h-32 object-contain"
            />
          </div>

          {/* Center content */}
          <div className="flex-1 flex flex-col items-center px-2">
            {/* Balloons */}
            <div className="mb-2 md:mb-4">
              <img src={balloonImage} alt="Hot air balloons" className="h-10 md:h-16 w-auto" />
            </div>

            {/* Main heading */}
            <h1
              className="text-2xl sm:text-3xl md:text-4xl text-[#b8a894] mb-1 md:mb-2 text-center"
              style={{ fontFamily: "'Fredericka the Great', cursive" }}
            >
              JOVY THOMAS VISUALS
            </h1>

            {/* Tagline */}
            <p
              className="text-xs md:text-sm text-[#9a9a9a] mb-2 md:mb-3 text-center"
              style={{ fontFamily: "'Courier New', monospace" }}
            >
              Preserve those moments forever...
            </p>

            {/* Location */}
            <p
              className="text-xs md:text-sm text-[#6b6b6b] text-center px-2"
              style={{ fontFamily: "'Courier New', monospace" }}
            >
              Hendersonville-TN-Portrait and Small event Photographer
            </p>
          </div>

          {/* Right badge - hidden on mobile, visible on md+ */}
          <div className="hidden md:block flex-shrink-0">
            <img
              src={portraitMasterBadge}
              alt="Portrait Masters Bronze 2021"
              className="w-20 lg:w-32 h-20 lg:h-32 object-contain"
            />
          </div>
        </div>
      </div>

      {/* Navigation menu */}
      <nav className="border-t border-[#c4b8a4]">
        <div className="max-w-7xl mx-auto px-4">
          {/* Mobile menu button */}
          <div className="md:hidden flex justify-center py-2">
            <button
              onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
              className="flex items-center gap-2 px-4 py-2 text-[#8b7355] border border-[#c4b8a4] bg-white"
              style={{ fontFamily: "'Courier New', monospace" }}
            >
              {mobileMenuOpen ? <X className="w-5 h-5" /> : <Menu className="w-5 h-5" />}
              <span className="text-sm">Menu</span>
            </button>
          </div>

          {/* Mobile menu dropdown */}
          {mobileMenuOpen && (
            <div className="md:hidden pb-4">
              <ul className="flex flex-col items-center gap-2">
                {menuItems.map((item, index) => (
                  <li key={index} className="w-full max-w-xs">
                    <button
                      onClick={() => {
                        onNavigate(item);
                        setMobileMenuOpen(false);
                      }}
                      className={`w-full px-4 py-2 text-sm transition-colors border border-[#c4b8a4] ${
                        currentPage === item
                          ? "text-[#8b7355] bg-[#f5f2ec]"
                          : "text-[#6b6b6b] bg-white hover:text-[#8b7355] hover:bg-[#f5f2ec]"
                      }`}
                      style={{ fontFamily: "'Courier New', monospace" }}
                    >
                      {item}
                    </button>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Desktop menu */}
          <ul className="hidden md:flex items-center justify-center gap-1 py-2 flex-wrap">
            {menuItems.map((item, index) => (
              <li key={index}>
                <button
                  onClick={() => onNavigate(item)}
                  className={`px-3 py-1 text-xs transition-colors border border-[#c4b8a4] ${
                    currentPage === item
                      ? "text-[#8b7355] bg-[#f5f2ec]"
                      : "text-[#6b6b6b] bg-white hover:text-[#8b7355] hover:bg-[#f5f2ec]"
                  }`}
                  style={{ fontFamily: "'Courier New', monospace" }}
                >
                  {item}
                </button>
              </li>
            ))}
          </ul>
        </div>
      </nav>
    </header>
  );
}
