// src/lib/components/Hero.svelte
<section class="container-wide px-4 py-8 md:py-16">
  <div class="text-center">
    <h2 class="heading-display text-3xl md:text-5xl text-brand mb-4 md:mb-6">Welcome</h2>
    <p class="text-base md:text-lg text-content max-w-2xl mx-auto mb-4 px-2">
      Capturing life's precious moments through the lens. Specializing in portraits and small
      event photography in the Hendersonville area.
    </p>
    <div class="text-xs md:text-sm text-brand max-w-3xl mx-auto px-2 space-y-2">
      <p>
        Professional family photographer serving Tennessee and Gallatin | Kids and child portrait
        photography | Maternity photography | Outdoor photography sessions | Fashion portfolio
        photography
      </p>
      <p class="text-xs">
        Serving Hendersonville, Gallatin, and surrounding Tennessee areas with professional
        photography services
      </p>
    </div>
  </div>
</section>

// src/components/Hero.tsx
export function Hero() {
  return (
    <section className="max-w-7xl mx-auto px-4 py-8 md:py-16">
      <div className="text-center">
        <h2 className="text-3xl md:text-5xl text-[#8b7355] mb-4 md:mb-6">Welcome</h2>
        <p className="text-base md:text-lg text-[#6b6b6b] max-w-2xl mx-auto mb-4 px-2">
          Capturing life's precious moments through the lens. Specializing in portraits and small
          event photography in the Hendersonville area.
        </p>
        <div
          className="text-xs md:text-sm text-[#8b7355] max-w-3xl mx-auto space-y-2 px-2"
          style={{ fontFamily: "'Courier New', monospace" }}
        >
          <p>
            Professional family photographer serving Tennessee and Gallatin | Kids and child
            portrait photography | Maternity photography | Outdoor photography sessions | Fashion
            portfolio photography
          </p>
          <p className="text-xs">
            Serving Hendersonville, Gallatin, and surrounding Tennessee areas with professional
            photography services
          </p>
        </div>
      </div>
    </section>
  );
}
